TASK1:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: data/VQA
  features_h5path1: data/coco/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK2:
  name: GenomeQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 2
  dataroot: /checkpoint/vedanuj/datasets/visual_genome/
  features_h5path1: /checkpoint/vedanuj/datasets/visual_genome/vg_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK3:
  name: VisualDialog
  type: VL-logit
  loss: CrossEntropyLoss
  process: dialog
  task_id: 3
  dataroot: data/VisualDialog
  features_h5path1: data/coco/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: 'data/VisualDialog/visdial_1.0_train.json'
  val_annotations_jsonpath: 'data/VisualDialog/visdial_1.0_val.json'
  max_seq_length: 16
  max_region_num: 101
  batch_size: 1
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK4:
  name: Vissual7w
  type: VL-logit
  process: normal
  task_id: 4
  split: train
TASK5:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  process: expand
  task_id: 5
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 101
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 10
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK6:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  process: expand
  task_id: 6
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 80
  max_region_num: 101
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 10
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK7:
  name: RetrievalCOCO
  type: VL-logit
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 7
  dataroot: data/cocoRetreival
  features_h5path1: data/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: data/cocoRetreival/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/cocoRetreival/all_data_final_val_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 101
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: data/flickr30k
  features_h5path1: data/flickr30k/flickr30k.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: data/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/flickr30k/all_data_final_val_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 101
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK9:
  name: refcoco
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 9
  dataroot: data/referExpression
  features_h5path1: /srv/share/vgoswami8/refer_expression/refcoco/refcoco_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /srv/share/vgoswami8/refer_expression/refcoco/refcoco_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: data/referExpression
  features_h5path1: /srv/share/vgoswami8/refer_expression/refcoco+/refcoco+_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /srv/share/vgoswami8/refer_expression/refcoco+/refcoco+_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK11:
  name: refcocog
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 11
  dataroot: data/referExpression
  features_h5path1: /srv/share/vgoswami8/refer_expression/refcocog/refcocog_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: /srv/share/vgoswami8/refer_expression/refcocog/refcocog_gt_resnext152_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  train_split: train
  val_split: val
  start_iteration: 0
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK12:
  name: NLVR2
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 12
  dataroot: /srv/share/vgoswami8/nlvr2/
  features_h5path1: /srv/share/vgoswami8/nlvr2/nlvr2_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 101
  batch_size: 10
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK13: 
  name: VisualEntailment
  type: VL-tri-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 13
  dataroot: /srv/share/vgoswami8/visual_entailment/
  features_h5path1: /srv/share/vgoswami8/flickr30k/flickr30k_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: dev
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK14:
  name: GuessWhat
  type: VL-tri-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 14
  dataroot: /srv/share/vgoswami8/guesswhat/
  features_h5path1: /srv/share/vgoswami8/coco/features_100/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 25
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: valid
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK15:
  name: GQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  process: normal
  task_id: 15
  dataroot: /srv/share/vgoswami8/gqa/
  features_h5path1: /srv/share/vgoswami8/gqa/gqa_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 26
  max_region_num: 101
  batch_size: 64
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense
TASK16:
  name: Foil
  type: VL-binary-classifier
  loss: CrossEntropyLoss
  process: normal
  task_id: 1
  dataroot: data/Foil
  features_h5path1: data/coco/COCO_trainval_resnext152_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: 'data/Foil/foilv1.0_train_2017.json'
  val_annotations_jsonpath: 'data/Foil/foilv1.0_test_2017.json'
  max_seq_length: 20
  max_region_num: 101
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 20
  multi_task:
    ep_2: dense
    ep_10: sparse
    ep_20: dense