TASK0:
  name: ConceptualCaption
  type: L-classifier
  task_id: 0
  features_h5path: 
  train_file: 
  max_seq_length: 30
  batch_size: 128
  train_split: train
  eval_split: val
TASK1:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  task_id: 1
  dataroot: data/VQA
  features_h5path1: data/coco/coco_trainval.h5
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 37
  batch_size: 256
  train_split: trainval
  val_split: minval
  start_iteration: 0
TASK2:
  name: GenomeQA
  type: VL-classifier
  task_id: 2
  features_h5path: /srv/datasets/conceptual_caption/coco/coco_trainval.h5
  train_file: data/VQA/
  split: train
TASK3:
  name: VisualDialog
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 3
  dataroot: data/VisualDialog
  features_h5path1: data/coco/coco_trainval.h5
  features_h5path2: ''
  train_annotations_jsonpath: 'data/VisualDialog/visdial_1.0_train.json'
  val_annotations_jsonpath: 'data/VisualDialog/visdial_1.0_val.json'
  max_seq_length: 60
  max_region_num: 37
  batch_size: 64
  train_split: train
  val_split: val
  start_iteration: 0
TASK4:
  name: Vissual7w
  type: VL-logit
  task_id: 4
  split: train
TASK5:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 5
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.h5
  features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.h5
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 40
  max_region_num: 60
  batch_size: 64
  train_split: train
  val_split: val
  start_iteration: 0
TASK6:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 6
  dataroot: data/VCR
  features_h5path1: /srv/datasets/conceptual_caption/VCR_resnet101_faster_rcnn_genome.h5
  features_h5path2: /srv/datasets/conceptual_caption/VCR_gt_resnet101_faster_rcnn_genome.h5
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 80
  batch_size: 64
  train_split: train
  val_split: val
  start_iteration: 0
TASK7:
  name: RetrievalCOCO
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 7
  dataroot: data/cocoRetreival
  features_h5path1: data/coco/coco_trainval.h5
  features_h5path2: ''
  train_annotations_jsonpath: data/cocoRetreival/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/cocoRetreival/all_data_final_val_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 37
  batch_size: 64
  train_split: train
  val_split: val
  start_iteration: 0
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 8
  dataroot: data/flickr30k
  features_h5path1: data/flickr30k/flickr30k.h5
  features_h5path2: ''
  train_annotations_jsonpath: data/flickr30k/all_data_final_train_2014.jsonline
  val_annotations_jsonpath: data/flickr30k/all_data_final_val_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 37
  batch_size: 64
  train_split: train
  val_split: val
  start_iteration: 0
TASK9:
  name: refcoco
  type: V-logit
  loss: BCEWithLogitLoss
  task_id: 9
  dataroot: data/referExpression
  features_h5path1: data/referExpression/refcoco.h5
  features_h5path2: data/referExpression/refcoco_gt.h5
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 60
  batch_size: 256
  train_split: train
  val_split: val
  start_iteration: 0
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  task_id: 10
  dataroot: data/referExpression
  features_h5path1: data/referExpression/refcoco+.h5
  features_h5path2: data/referExpression/refcoco+_gt.h5
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 60
  batch_size: 256
  train_split: train
  val_split: val
  start_iteration: 0
TASK11:
  name: Refg
  type: V-logit
  task_id: 11
  split: train
TASK12:
  name: DenseCaptionRetrieval
  type: V-logit
  task_id: 12
  split: train
TASK13:
  name: Flickr30kGround
  type: L-logit
  task_id: 13
  split: train
TASK14:
  name: CocoCaption
  type: L-classifier
  task_id: 14
  split: train
TASK15:
  name: Flickr30kCaption
  type: L-classifier
  task_id: 15
  split: train
TASK16:
  name: NLVR2
  type: VL-logit
  task_id: 16
  split: train  